### PR TITLE
README: Fix typo

### PR DESCRIPTION
**Pull request by Turbo87**
... and adjust heading level (`##` is h2, which is the same as `-----`, but this should have been h3)

### CODE REVIEW

**Review by rwjblue — APPROVED** [review]

**Comment by pzuraq** [comment]
Test failures are due to the same issue upstream with `transform-template-literals`. I think we need to fix this issue upstream, and backport it to the native class polyfill versions, before we can fix the tests here.

**Comment by Turbo87** [comment]
@pzuraq can we merge this docs fix or do you want to wait for CI to be green?

**Comment by pzuraq** [comment]
master was fixed upstream, so I just need to update this, and then CI will be green and good to go. Will get to it today

**Comment by Turbo87** [comment]
@pzuraq any news on this?

**Comment by Turbo87** [comment]
🤷‍♂

**Pull request closed without merging**
